<?php
/**
 * Digit Software Solutions..
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category   Dss
 * @package    Dss_Limitcartqty
 * @author     Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<?php
/** @var $block \Dss\Limitcartqty\Block\MinMaxCart */
?>
<?php if (!$block->hasError()): ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
<ul class="checkout methods items checkout-methods-items">
    <?php foreach ($methods as $method): ?>
        <?php if ($methodHtml = $block->getMethodHtml($method)): ?>
            <?php if ($block->getCheckoutFlag()): ?>
                <li class="item"><?= /* @noEscape */ $methodHtml ?></li>
            <?php endif; ?>
    <?php endif; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>

